version: '3'

services:
  postgres:
    container_name: postgres-container
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      # POSTGRES_DB: "orders"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    networks:
      - app-network
    volumes:
      - ./dbdata/postgres:/var/lib/postgresql
      
  pg-admin:
    container_name: db-admin-container
    image: dpage/pgadmin4
    ports: 
      - "8081:80"
    depends_on: 
      - postgres
    volumes:
      - ./dbdata/pgadmin:/var/lib/pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin
      PGADMIN_DEFAULT_PASSWORD: p@ssword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge